# Cloudflare Workers 配置文件
# 用途：配置 Cloudflare Workers 部署参数

name = "api-proxy-gateway-service"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 构建配置
[build]
command = "npm run build"

# 环境变量
[env.production.vars]
NODE_ENV = "production"
LOG_LEVEL = "warn"
LOAD_BALANCE_STRATEGY = "round_robin"
CIRCUIT_BREAKER_FAILURE_THRESHOLD = "3"
CIRCUIT_BREAKER_RESET_TIMEOUT = "60000"
GEMINI_BASE_URL = "https://generativelanguage.googleapis.com"
GEMINI_API_VERSION = "v1beta"
GEMINI_TIMEOUT = "30000"
CORS_ORIGIN = "*"
HELMET_ENABLED = "true"
RATE_LIMIT_ENABLED = "true"
MONITORING_ENABLED = "true"

[env.development.vars]
NODE_ENV = "development"
LOG_LEVEL = "debug"
LOAD_BALANCE_STRATEGY = "round_robin"
CIRCUIT_BREAKER_FAILURE_THRESHOLD = "3"
CIRCUIT_BREAKER_RESET_TIMEOUT = "60000"
GEMINI_BASE_URL = "https://generativelanguage.googleapis.com"
GEMINI_API_VERSION = "v1beta"
GEMINI_TIMEOUT = "30000"
CORS_ORIGIN = "*"
HELMET_ENABLED = "false"
RATE_LIMIT_ENABLED = "false"
MONITORING_ENABLED = "true"

# KV 存储（可选，用于缓存和统计）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects（可选，用于状态管理）
# [[durable_objects.bindings]]
# name = "CIRCUIT_BREAKER"
# class_name = "CircuitBreakerDO"

# 路由配置
[[routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

# 定时任务配置（可选）
[triggers]
crons = ["0 */6 * * *"]  # 每6小时执行一次清理任务
